### ISSUE TITLE
load_read: Error loading read "ffa76442-39ea-4a9b-8203-04eadd98f90d" from file "./batch_0.fast5": Fast5 read file is invalid. Raw data field 'median_before' has wrong type.

### ISSUE THREAD

**Issue by Bessyyi** [kpalin/gcf52ref#4]
Hello,professor!When i guppy my .fast5 file,i get the error.Can you give me some advice?Thanks!
![2](https://user-images.githubusercontent.com/73151161/126420570-59b3c94b-d826-4b1e-b317-ca069d10276f.PNG)

**Comment by kpalin** [comment]
Hi Bessyyi,

I can't help you. Guppy is ONT software so you need to contact support at nanoporetech.com for help.
